### ISSUE TITLE
supervisor process uvcsite is broken, missing unicorn server 

### ISSUE THREAD

**Issue by joka** [novareto/uvckickstart#2]
The buildout generated by uvcproject is creating a supervisor process 'uvcsite'.
This process is using 'gunicorn' to run uvcsite, but unicorn is not installed:
```
bin/supervisorctl status                                                                                                                130 ↵ ✭
uvcsite                          FATAL     can't find command '/home/joka/dev/zope/bghw/uvckickstart/porta
```
This is a regression caused by cea9ede5c20172f5ab7d8bd4a2af19f8e7c35f2c

**Comment by goschtl** [comment]
Good Catch... We decided to drop gunicorn and use paster again. I will fix it...

**Comment by goschtl** [comment]
fixed, but it needs a new release...

**Comment by joka** [comment]
outdated
